sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/server.js .
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/setting.js .
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/CheckEveryThing.js .
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/salaryCalculate.js .
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/AddInformationFromWebsite.js .
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/CheckInformationFromWebsite.js .
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/AdjustInformationFromWebsite.js .

sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/AddEmployeeWorkSchedule.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/AdjustOnlineStatus.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/AdjustWorkSchedule.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/CheckEveryMonthWorkStatus.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/CheckEveryDayWorkStatus.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/CheckWorkSchedule.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/index.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/MonthSalary.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/PrintSalaryCalculate.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/UseCheckBoxByAddEmployeeWorkSchedule.ejs ./views/.
sudo cp ./../../../../Library/WebServer/Documents/Project/NodeGo/views/CheckEmployeeBasicInformation.ejs ./views/.
